name: Vérification arborescence
on:
  pull_request:
    branches:
      - main

jobs:
  verify-structure:
    runs-on: windows-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v2
      - name: Vérification de l’arborescence
        run: |
          test -d site/img && test -d site/css && test -d site/js && test -d src
          find site -type f ! -name "*.html" ! -name "*.php" -exec false {} +
          find site/img -type f ! -name "*.png" ! -name "*.jpg" -exec false {} +
          find site/css -type f ! -name "*.css" -exec false {} +
          find site/js -type f ! -name "*.js" -exec false {} +
