name: Vérification du code PHP avec PHPCS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_php:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification des fichiers du dépôt
        uses: actions/checkout@v2

      - name: Configurer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Installer les dépendances PHP
        run: composer install

      - name: Exécuter PHP CodeSniffer (PHPCS)
        run: ./vendor/bin/phpcs chemin/vers/vos/fichiers