name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: |
          composer install --no-dev

      - name: Make phpcs executable
        run: chmod +x vendor/bin/phpcs

      - name: Run PHPCS linting
        run: |
          vendor/bin/phpcs --standard=PSR2 src/MesDates.php

      - name: Run PHPUnit tests
        run: |
          vendor/bin/phpunit
