name: Lint et Tests

on: 
  push:
    branches:
      - main  # ou la branche où tu veux que l'action s'exécute
  pull_request:
    branches:
      - main  # ou la branche de ton choix

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installer Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Lint PHP Code avec PHP_CodeSniffer
      run: |
        composer install
        ./vendor/bin/phpcs --standard=PSR12 src/

  tests:
    runs-on: ubuntu-latest
    needs: lint  # Assure que les tests ne s'exécutent qu'après que le lint ait réussi
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installer Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Installer PHPUnit
      run: |
        composer require --dev phpunit/phpunit

    - name: Exécuter les tests PHPUnit
      run: |
        ./vendor/bin/phpunit --testdox tests/MesDatesTest.php
