name: Lint and Test Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, bcmath

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-dev

      # Lint the PHP code
      - name: Lint PHP code
        run: vendor/bin/phpcs --standard=PSR12 src/

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
