name: Lint PHP Code

on: [push]

jobs:
  phpcs:
    name: Run PHPCS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=PSR2 src/MesDates.php
