name: Linter avec PHPCS

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer PHP et Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer, phpcs

      - name: Installer les dépendances PHP
        run: composer install --no-progress --no-suggest

      - name: Lancer PHPCS
        run: vendor/bin/phpcs --standard=PSR2 src/MesDates.php

