name: Lister les fichiers

on: 
  push:
    branches:
      - mes-dates
jobs:
  afficher-fichiers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Afficher les fichiers du repo
        run: ls -la
