name: Lister les fichiers

on: 
  push:   # Cela indique que le workflow se déclenche sur un push
    branches:
      - main   # Le workflow sera déclenché pour les pushs vers la branche "main"

jobs:
  afficher-fichiers:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Afficher les fichiers du repo
        run: ls -la
