<<<<<<< HEAD
name: Linter avec PHPCS

on: [push]
=======
name: Lister fichiers et Linting avec PHPCS

on:
  push:
    branches:
      - mes-dates
>>>>>>> 9adeee8b9a469dc7922da0ff7adb05314ce27c7d

jobs:
  linter:
    runs-on: ubuntu-latest
<<<<<<< HEAD

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer PHP et Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer, phpcs

      - name: Installer les dépendances PHP
        run: composer install --no-progress --no-suggest

      - name: Lancer PHPCS
        run: vendor/bin/phpcs --standard=PSR2 src/MesDates.php

=======
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lister les fichiers
        run: ls -la

      - name: Installer PHP_CodeSniffer
        run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

      - name: Linter le code avec PHPCS
        run: php phpcs.phar --standard=PSR12 .
>>>>>>> 9adeee8b9a469dc7922da0ff7adb05314ce27c7d
