name: Vérification du code avec PHPCS

on:
  push:
    branches:
      - mes-dates

jobs:
  linter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
        
      - name: Installer PHP et PHPCS
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          chmod +x phpcs.phar
          mv phpcs.phar /usr/local/bin/phpcs

      - name: Lancer PHPCS
        run: phpcs --standard=PSR12 src/

      - name: Afficher les fichiers du repo
        run: ls -la