name: Vérification du code avec PHPCS

on: 
  push:
    branches:
      - mes-dates

jobs:
  linter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      
      - name: Installer PHP et PHPCS
        run: |
          sudo apt-get update  # Met à jour la liste des paquets
          sudo apt-get install -y php-cli  # Installe PHP
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar  # Télécharge PHPCS
          chmod +x phpcs.phar  # Rends PHPCS exécutable
          mv phpcs.phar /usr/local/bin/phpcs  # Déplace PHPCS dans un dossier accessible

      - name: Lancer PHPCS
        run: phpcs --standard=PSR12 src/

      - name: Afficher les fichiers du repo
        run: ls -la
